version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    ports:
      - "8081:8080"

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    ports:
      - "8082:8080"

  app3:
    build:
      context: .
      dockerfile: Dockerfile.app3
    ports:
      - "8083:8080"

  app4:
    build:
      context: .
      dockerfile: Dockerfile.app4
    ports:
      - "8084:8080"
